Replace `windows` dependency with checked-in bindings from `windows-bindgen`
Keeping the `windows` dependency up-to-date is tedious, and only really
necessary to reduce downstream duplicates on this relatively large crate
as no `windows` types are used in the public API of `generator`. As
shown by earlier PRs these newer versions can trivially be used from a
version range without being affected by breaking changes within.

An alternative solution, proposed in this PR, is to use
`windows-bindgen` which inlines the bindings directly into `generator`
and removes the need for a direct dependency on `windows`.  Instead
only minimal shared code is used from `windows-link`, and by generating
`sys` bindings no `windows-core` dependency (releases mostly at the
same pace as `windows`) is needed to access `BOOL` and `Result`.  Other
alternatives include migrating to `windows-sys` which is a smaller
crate that releases at a slightly slower pace or figuring out how to
reference `BOOL` and `Result` from `windows-result` to get automatic
`GetLastError()` handling.

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -18,16 +18,18 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout sources
-        uses: actions/checkout@v2
-      - name: Install toolchain
-        uses: actions-rs/toolchain@v1
-        with:
-          profile: minimal
-          toolchain: stable
-          override: true
-          components: rustfmt, clippy
+        uses: actions/checkout@v5
       - name: Run cargo clippy
-        uses: actions-rs/cargo@v1
-        with:
-          command: clippy
-          args: -- -D warnings
+        run: cargo clippy -- -D warnings
+
+  generate-windows-bindings:
+    name: Generate Rust crate
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v5
+      - name: Clean
+        run: rm src/stack/windows_bindings.rs
+      - name: Generate
+        run: cargo r -p api_gen
+      - name: Diff generated Rust code
+        run: test -z "$(git status --porcelain)" || (echo "::error::Generated files are different, please regenerate with cargo run -p api_gen!"; git status; false)
